# Generated by Django 3.2.8 on 2021-10-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_rename_results_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='points',
            field=models.IntegerField(),
        ),
    ]
