# Generated by Django 3.2.8 on 2021-10-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_auto_20211024_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
